# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MAILER_DSN: ${MAILER_DSN}
      MAILER_SENDER: ${MAILER_SENDER}
      SENTRY_DSN: ${SENTRY_DSN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tvdt.rule=Host(`tijdvoordetest.nl`)"
      - "traefik.http.routers.tvdt.entrypoints=websecure"
      - "traefik.http.routers.tvdt.tls.certresolver=marijndoeve"
      - "traefik.http.routers.tvdt.service=tvdt"
      - "traefik.http.services.tvdt.loadbalancer.server.port=80"
    networks:
      - web
      - internal
  database:
    networks:
      - internal
networks:
  web:
    external: true
  internal:
    external: false  
