# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`tijdvoordetest.nl`)"
      - "traefik.http.routers.php.entrypoints=websecure"
      - "traefik.http.routers.php.tls.certresolver=marijndoeve"
      - "traefik.http.services.php.loadbalancer.server.port=80"
    networks:
      - web
      - internal
networks:
  web:
    external: true
  internal:
    external: false  
