<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** Auto-generated Migration: Please modify to your needs! */
final class Version20260705142023 extends AbstractMigration
{
    #[\Override]
    public function getDescription(): string
    {
        return 'Fix ext_log_entries id to IDENTITY, data to JSON, and drop slug default';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ext_log_entries ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ext_log_entries ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE ext_log_entries ALTER data TYPE JSON USING data::json');
        $this->addSql('ALTER TABLE question_label ALTER slug DROP DEFAULT');
    }

    #[\Override]
    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ext_log_entries ALTER data TYPE TEXT');
        $this->addSql("ALTER TABLE ext_log_entries ALTER id SET DEFAULT nextval('ext_log_entries_id_seq'::regclass)");
        $this->addSql('ALTER TABLE ext_log_entries ALTER id DROP IDENTITY');
        $this->addSql("ALTER TABLE question_label ALTER slug SET DEFAULT ''");
    }
}
